#!/bin/bash

mkdir release 2> /dev/null
rm -rf release/* 2> /dev/null

lua manager.lua -b -o "exe/officialloadorder.txt"

cp -r var/libertica release
cp changelog.md release
cp -r api release && mv release/api release/libertica_api

lua manager.lua -b -s -o "exe/officialloadorder.txt"
mkdir release/single
cp -r "var/qsb.lua" "release/single/qsb.lua"
cp -r "var/localmapscript.lua" "release/single/localmapscript.lua"
cp -r "var/mapscript.lua" "release/single/mapscript.lua"

cp readme_release.md release && mv release/readme_release.md release/readme.md
cp instructions_de.md release
cp instructions_en.md release